### ISSUE TITLE
Would you like to use a newer cunit?

### ISSUE THREAD

**Issue by inorton** [k0ekk0ek/conan-cunit#1]
Hi,  I just found your project. It's great you have cunit and conan working together, A few months ago I decided for fork cunit to fix some old compiler warnings and to finish off it's junit xml report format. I also decided to migrate cunit's build system to cmake so it would be great to share ideas.  

I maintain "cunity cunit" over on gitlab at https://gitlab.com/cunity/cunit  which is CI built for windows and 32/64 linux and if I get time perhaps x64 solaris 11 soon.

I have a "classic-cunit" branch which is compatible with the last release of cunit from sourceforge and has only had minor code fixes.

**Comment by k0ekk0ek** [comment]
Hi. Good to hear you find this little Conan recipe useful. If you want I can accept patches (in the form of a pull-request) to the Conan recipe (if they're good) so CUnit gets patched by Conan before compiling. I'd rather not switch sources. The best way of course would be to upstream the changes to CUnit itself.

**Comment by inorton** [comment]
Upstreaming was my intention, but the sourcecforge team for cunit have long since gone away, so I have committed myself to the future maintenance of cunit.

**Comment by k0ekk0ek** [comment]
Hi @inorton. The best thing to do in that case is probably get yourself accepted as a developer. Maybe sent one of the "active" developers a message? I saw your comment on the CUnit forums. I agree that there hasn't been much activity, but it's the official home and I don't feel comfortable switching repositories. I'll be happy to update the recipe once the official port switches. Of course, I'll still accept pull requests with patches that are applied during package creation. Maybe I should ask _Bincrafters_ to adopt the recipe, so that more people will find it.

**Comment by k0ekk0ek** [comment]
I'm closing this issue with won't fix. If you have any pull-requests or other issues, please submit them to the bincrafters conan-cunit repository.
